### ISSUE TITLE
T_YIELD_FROM is not recognized and breaks code

### ISSUE THREAD

**Issue by r4ndsen** [nanch/phpfmt_stable#37]
```php
function b()
{
    yield from a();
}
```
results in
```php
function b()
{
    yield froma();
}
```

removing the space and breaking the actual logic.
i believe it would be enough to just define T_YIELD_FROM in the tokenizer. 
token id is 269

//edit: running on php7.1.11 

thanks

**Comment by MKCG** [comment]
It seems that PHPFMT is not compatible with PHP 7.1

This issue is caused by the fact that "yield from" produces the token T_YIELD_FROM but this token is not yet managed by phpfmt.

I made a quick fix which does not seems to have any side effect.

I uncompressed the fmt.phar to have access to fmt.stub.php and then I simply added the following lines before the default case of ResizeSpaces::format : 

```php
case T_YIELD_FROM:
    $this->appendCode($text . $this->getSpace($this->rightTokenIs(T_STRING)));
    break;
```

The updated fmt.phar and the script used to update its content are both available here : https://github.com/MKCG/phpfmt_7-1

**Comment by r4ndsen** [comment]
works great, thank you.
